### ISSUE TITLE
rf-fold is not working with my xml reactivity file?

### ISSUE THREAD

**Issue by adiroy92** [dincarnato/RNAFramework#45] opened 2023-10-09 11:33 UTC
Hi Danny, previously i had a issue that i have successfully overcome. Sorry for not getting back to you about this. Right now, I have successfully generated normalized chemical reactivity files (.xml) of my sequencing data by following your application note. However, when i am trying to generate the structure from my xml files using basic rf-fold command (rf-fold -g file.xml) it is showing folding is failed. My software installation is seems fine because the same rf-fold command (rf-fold -g 23S.xml) is generating a rf-fold folder with output as a dot bracket file (23S.db) and 23S.svg image file. I got this 23S.xml file from your shared data. The xml files i have generated and 23S.xml seem similar to me in term of file format. I am sharing with you the google drive link of the folder containing my xml files: https://drive.google.com/drive/folders/1C4ViVDbgmBtZ3UQxUjJUg802_H2K8ywB?usp=drive_link. Please have a look and give me suggestions to overcome the issue. Thank you very much !

**Comment by dincarnato** [comment] 2023-10-09 11:59
Dear adiroy92,

the issue is with your sequence ids. The ":" characters are messing with some of the commands.
Please make sure that the sequence IDs in your starting fasta file do not contain any special character (other than . _ -) and rerun the analysis.
In the meantime, you can run the following from within your xml folder (I am assuming you are working on Linux);

```bash
for f in *.xml; do sed -i 's/:/_/g' $f; done
```

**Comment by adiroy92** [comment] 2023-10-11 11:32
Thank you  very much Danny for your suggestions! Your code worked perfectly.

**Comment by dincarnato** [comment] 2023-10-11 12:30
Great :-) Closing the issue now!

**Closed** 2023-10-11 12:31 UTC
