### ISSUE TITLE
Issue with RNAFramework installation

### ISSUE THREAD

**Issue by Frappadoo** [dincarnato/RNAFramework#63] opened 2024-06-27 08:51 UTC
Hi Danny,

I have recently tried to install RNAFramework on a CentOS, however, I can't seem to get it to run, as every time I try to run it, it gives me the following error. 

-bash: rf-map: command not found

Do you have any suggestions on how to solve this? 

Thank you, 

Fran

**Comment by dincarnato** [comment] 2024-06-27 08:58
Hi Fran,

it looks like you haven't added the RNAFramework install dir to your PATH.

Best,
Danny

**Comment by dincarnato** [comment] 2024-06-27 10:31
Francesca,

the error comes from your system, not the RNA Framework.
Where is your RNAFramework install dir located?
Can you paste here the output of the following command:

`echo $PATH`

Best,
Danny

**Comment by Frappadoo** [comment] 2024-06-27 11:10
Hi Danny, this is the output
echo $PATH
/nobackup/leedsomics_tools/RNAFramework:/nobackup/leedsomics_tools/shapemapper2:/nobackup/leedsomics_tools/RNAFramework:/nobackup/leedsomics_tools/shapemapper2:/nobackup/bsjma_relion4/relion/build/bin/:/apps/mpi/bin:/apps/developers/libraries/openmpi/3.1.4/1/intel-19.0.4/bin:/apps/developers/compilers/intel/19.0.4/1/default/compilers_and_libraries_2019.4.243/linux/bin/intel64:/apps/developers/compilers/intel/19.0.4/1/default/debugger_2019/gdb/intel64/bin:/services/sge_prod/bin/lx-amd64:/services/sge_prod/default/common/leeds/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/apps/bin:/nobackup/leedsomics_tools/RNAFramework/


Best, 

Fran

**Comment by dincarnato** [comment] 2024-06-27 11:13
I assume RNAFramework is inside `/nobackup/leedsomics_tools/RNAFramework/`. Can you also do:

`ls -l /nobackup/leedsomics_tools/RNAFramework/`

**Comment by Frappadoo** [comment] 2024-06-27 11:15
Ah got it looks like I don't have permission:

ls -l /nobackup/leedsomics_tools/RNAFramework/
ls: cannot open directory /nobackup/leedsomics_tools/RNAFramework/: Permission denied

**Comment by dincarnato** [comment] 2024-06-27 12:17
Great. Feel free to close the issue if solved.

**Comment by Frappadoo** [comment] 2024-06-28 09:53
Hi Danny, 

I got permission to the files now and have checked that RNAFramework is in my PATH, but it is still giving me the same error.

**Comment by dincarnato** [comment] 2024-06-28 09:57
This is an error caused by the way things are configured on your system, non an RNAFramework issue. Your system administrator is the best person to ask for help.

Anyway, can you share the output of the command?

`ls -l /nobackup/leedsomics_tools/RNAFramework/`

**Comment by Frappadoo** [comment] 2024-06-28 12:06
ls -l /nobackup/leedsomics_tools/RNAFramework/
total 744
-rwxr-xr-x  1 fbsev fbs 24726 Jun  7 15:14 CHANGELOG.md
-rwxr-xr-x  1 fbsev fbs   372 Jun  7 15:14 index.rst
drwxr-xr-x 11 fbsev fbs  4096 Jun  7 15:14 lib
-rwxr-xr-x  1 fbsev fbs 35797 Jun  7 15:14 LICENSE
-rwxr-xr-x  1 fbsev fbs  2139 Jun  7 15:14 README.md
-rwxr-xr-x  1 fbsev fbs 19762 Jun  7 15:14 rf-combine
-rwxr-xr-x  1 fbsev fbs 13875 Jun  7 15:14 rf-compare
-rwxr-xr-x  1 fbsev fbs 16059 Jun  7 15:14 rf-correlate
-rwxr-xr-x  1 fbsev fbs 54987 Jun  7 15:14 rf-count
-rwxr-xr-x  1 fbsev fbs 52249 Jun  7 15:14 rf-count-genome
-rwxr-xr-x  1 fbsev fbs 56560 Jun  7 15:14 rf-duplex
-rwxr-xr-x  1 fbsev fbs 12409 Jun  7 15:14 rf-eval
-rwxr-xr-x  1 fbsev fbs 75410 Jun  7 15:14 rf-fold
-rwxr-xr-x  1 fbsev fbs 23765 Jun  7 15:14 rf-index
-rwxr-xr-x  1 fbsev fbs 16535 Jun  7 15:14 rf-jackknife
-rwxr-xr-x  1 fbsev fbs 34942 Jun  7 15:14 rf-json2rc
-rwxr-xr-x  1 fbsev fbs 33465 Jun  7 15:14 rf-map
-rwxr-xr-x  1 fbsev fbs 14769 Jun  7 15:14 rf-modcall
-rwxr-xr-x  1 fbsev fbs 27294 Jun  7 15:14 rf-motifdiscovery
-rwxr-xr-x  1 fbsev fbs 37897 Jun  7 15:14 rf-mutate
-rwxr-xr-x  1 fbsev fbs 37659 Jun  7 15:14 rf-norm
-rwxr-xr-x  1 fbsev fbs 21025 Jun  7 15:14 rf-normfactor
-rwxr-xr-x  1 fbsev fbs 36205 Jun  7 15:14 rf-peakcall
-rwxr-xr-x  1 fbsev fbs 14882 Jun  7 15:14 rf-rctools
-rwxr-xr-x  1 fbsev fbs 20974 Jun  7 15:14 rf-structextract
-rwxr-xr-x  1 fbsev fbs  8880 Jun  7 15:14 rf-wiggle
drwxr-xr-x  2 fbsev fbs  4096 Jun  7 15:14 tests
-rwxr-xr-x  1 fbsev fbs     7 Jun  7 15:14 VERSION

**Comment by dincarnato** [comment] 2024-06-28 12:45
If you `echo $PATH` is the path to RNAFramework still there?

**Comment by Frappadoo** [comment] 2024-06-28 13:00
Yes it is still there

**Comment by Frappadoo** [comment] 2024-06-28 13:10
/nobackup/leedsomics_tools/RNAFramework/rf-map -h
: No such file or directory

**Comment by dincarnato** [comment] 2024-06-28 13:12
And if you do `ls -l /nobackup/leedsomics_tools/RNAFramework/rf-map`

**Comment by Frappadoo** [comment] 2024-06-28 13:17
ls -l /nobackup/leedsomics_tools/RNAFramework/rf-map-rwxr-xr-x 1 fbsev fbs 33465 Jun  7 15:14 /nobackup/leedsomics_tools/RNAFramework/rf-map

**Comment by dincarnato** [comment] 2024-06-28 13:18
Francesca, I am sorry but this is clearly an issue with permissions on your server. The folder is in your path, you can list its content, the files are executable, but apparently you can't execute them, which has nothing to do with RNA Framework. You should contact your server admin and have it fixed. 

It is unclear to me how did you manage to clone the git repo, if you could not even list the directory content.
My suggestion is to git clone the repo inside your home directory and try again. 

Best, Danny

**Comment by Frappadoo** [comment] 2024-06-28 13:20
I'll contact the administrator that has installed this and ask to get permission. Thank you for your help

**Closed** 2024-06-28 13:21 UTC
