### ISSUE TITLE
unsupported line endings ("\r") when running rf-count

### ISSUE THREAD

**Issue by sjhuang6** [dincarnato/RNAFramework#13] opened 2021-07-27 15:27 UTC
Hi Danny, 

A RNAFramework rookie here. I was running the rf-count to map the mutation: 
rf-count -p 12 -f .fa -m -mm -ow /Denatured.bam /1M7.bam /Untreated.bam

It gives me this error message: 
[+] Making output directory...
[+] Guessing file types:

  Sample       Type    5'-end trimming

  Denatured    BAM     Ignored
  1M7          BAM     Ignored
  Untreated    BAM     Ignored

[+] Getting transcripts from reference, and building count table base structure...
[!] Exception [Data::IO::Sequence->new()]:
    File contains unsupported line endings ("\r")
    -> Caught at /RNAFramework/lib/Core/Base.pm line 126.

Any idea how to solve this problem? Great software package by the way. Really appreciate your effort. 

Best,
Jimmy Huang

**Comment by dincarnato** [comment] 2021-07-27 15:48
Hi Jimmy,

Thanks for your request.
How has your BAM file been generated? Can you please share the input files and the exact command line so that I can try reproduce the issue? What OS are you working on?

Best,
Danny

**Comment by sjhuang6** [comment] 2021-07-27 16:14
The BAM files were generated using rf-map: 
rf-map -p 12 -b2 -cqo -cq5 20 -bs -bl 15 -bN 1 -bD 20 -bR 3 -bdp 100 -bma 2 -bmp 6,2 -bdg 5,1 -bfg 5,1 -mp "--maxins 100" -ow -bi /RNAFramework/index /RNAFramework/Denatured_R1.fastq /RNAFramework/1M7_R1.fastq /RNAFramework/Untreated_R1.fastq
I think I just copied the example commend from the SHAPE-Map example. 

I'm working on a linux cluster. For the input files, do you mean the fastq files (1M7_R1.fastq...) ? They are fairly large (~17G) and I will have to find a way to share them if you really need them. These fastq files were trimmed with cutadapt before being inputted  into the rf-map.

**Comment by dincarnato** [comment] 2021-07-27 17:37
The issue seems to be caused by the reference transcripts' file (FASTA
File). Was that file perhaps generated or edited on Mac? If you can send me the file I can fix it for you, otherwise you can use the dos2unix utility, which I guess should be able to fix also the "\r" line endings.

**Comment by sjhuang6** [comment] 2021-07-27 18:00
Yes, you are right, it was caused by the fasta file format. dos2unix can solve the problem. Thanks very much for your time!

**Comment by dincarnato** [comment] 2021-07-27 18:01
Ok great!
I'll now close the issue.
All the best,

Danny

**Closed by dincarnato** 2021-07-27 18:01 UTC
