### ISSUE TITLE
rf-wiggle outputs ratios greater than 1. 

### ISSUE THREAD

**Issue by mohamedbahru** [dincarnato/RNAFramework#50] opened 2024-01-02 07:45 UTC
Hi,
I used rf-wiggle with a flag -r to get the mutation ratio from .rc file.

I found a lot of mutation ratios greater than 1. Shouldn't the mutation ratio values should be between 0 and 1?

In the IGV viewer, I looked at the alignments. I found that those sites that are having very high ratios (>500) are having 0 read coverage in the IGV viewer. 

In my case, I have long reads from oxford nanopore sequencing, aligned to the genome (alignment with splicing enabled) using minimap2 aligner. I did the mutation counting using rf-count-genome tool. 

Have I done something wrong?

Could you please help me?

Thanks,
Mohamed

**Comment by dincarnato** [comment] 2024-01-02 17:31
Mohamed,

I doubt the issue is with rf-wiggle. Something is going on with minimap + rf-count.
Can you please share with me a sample BAM file that is giving the issue, plus the reference fasta file? I will see what's going on.

Also, keep in mind that IGV doesn't show all the reads. Some reads are not displayed due to certain filters.

Best,
Danny

**Comment by mohamedbahru** [comment] 2024-01-03 13:45
Hi Danny,

Thanks for your reply.
Could you let me know, how I should send the bam file and the reference fasta file?

Thanks and regards,
Mohamed

**Comment by dincarnato** [comment] 2024-01-03 16:20
Just send it to me at dincarnato@rnaframework.com

**Comment by dincarnato** [comment] 2024-01-05 14:53
Not sure if you sent it but I didn't receive anything yet. You can also use drive.

**Comment by mohamedbahru** [comment] 2024-01-05 15:05
Sorry for the late reply. I have sent to your email. Have you received the data?

**Comment by dincarnato** [comment] 2024-01-08 12:27
Can you give me the exact command line you are using with rf-count-genome so that I can reproduce the issue?

**Comment by mohamedbahru** [comment] 2024-01-08 12:55
rf-count-genome -p 6 -o q_0_eq_0 -ow -f mm39.fa -m -nd -ni -q 0 -eq 0 filtered.bam:u > error.log

**Comment by dincarnato** [comment] 2024-01-08 12:57
Ok thanks. Will investigate, but taking a quick look at your BAM file I suspect it might be linked to very large insertions. Can you try to map your reads to the sole transcript and run rf-count instead and see if the issue occurs there as well?

**Comment by dincarnato** [comment] 2024-01-08 13:31
It just finished running smoothly:

```
[+] Statistics:

  [*] Sample "Map.sorted": 16553 transcripts covered [A: 22.81; C: 30.32; G: 18.66; T: 28.21]

[+] Cleaning up temporary files...
[+] All done.
```

Please make sure you have the latest version of the RNA Framework (`git pull`) and a recent version of SAMTools.

**Comment by mohamedbahru** [comment] 2024-01-08 14:49
I used rf-wiggle with a flag -r to get the mutation ratio from .rc file.

I found a lot of mutation ratios greater than 1. Shouldn't the mutation ratio values should be between 0 and 1?

Could you please check the ratios?
Thanks.

**Comment by dincarnato** [comment] 2024-01-11 13:25
Hi Moahamed,

thanks for your patience.
The bug was caused by the multiple gaps in the reads (N cigar operations) that were not properly handled for reads harboring more than one.
It should have been fixed now.
Can you please try and let me know?

Thanks a lot for reporting this bug! It would have been almost impossible to catch without such a complex example.

All the best,
Danny

**Comment by mohamedbahru** [comment] 2024-01-11 14:13
Thanks Danny.  I will try the updated tool and let you know if there are any issues.

**Comment by mohamedbahru** [comment] 2024-01-15 07:25
Thanks Danny for your assistance. 
The tool works fine now.

**Comment by dincarnato** [comment] 2024-01-15 17:06
That's great.
Thanks for reporting the bug.

Best, Danny

**Closed by dincarnato** 2024-01-15 17:06 UTC
